FROM jhipster/jhipster

RUN mkdir jhipster-speedup \
 && cd jhipster-speedup \
 && wget https://github.com/jhipster/jhipster-travis-build/archive/master.zip \
 && unzip -qq master.zip \
 && rm master.zip \
 && ls && cd jhipster-travis-build-master && ls && pwd


