image: ogomez/jhipster-gitlab-ci

variables:
  - JHIPSTER_GATEWAY_APP: "gateway_application_name"
  - JHIPSTER_MICROSERVICE_APP: "microservice_application_name"
  - GITLAB_GROUP: "group"
  - GITLAB_PROJECT: "project"

stages:
  - build
  - deploy

gateway-build:
  stage: build
  script:
    - cd /$CI_PROJECT_DIR/$JHIPSTER_GATEWAY_APP
    - ./mvnw -Pprod package"
  artifacts:
    paths:
    - /$CI_PROJECT_DIR/$JHIPSTER_GATEWAY_APP/target/*.war

microservice-build:
  stage: build
  script:
    - cd /$CI_PROJECT_DIR/$JHIPSTER_MICROSERVICE_APP
    - ./mvnw -Pprod package"
  artifacts:
    paths:
    - /$CI_PROJECT_DIR/$JHIPSTER_MICROSERVICE_APP/target/*.war

gateway-deploy:
  image: ogomez/java-docker
  services:
    - docker:dind
  stage: deploy
  dependencies:
    - gateway-build
  script:
    - cd /$CI_PROJECT_DIR/$JHIPSTER_GATEWAY_APP
    - ./mvnw docker:build
    - docker tag frontend registry.gitlab.com/$GITLAB_GROUP/$GITLAB_PROJECT:$JHIPSTER_GATEWAY_APP
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/$GITLAB_GROUP/$GITLAB_PROJECT:$JHIPSTER_GATEWAY_APP

microservice-deploy:
  image: ogomez/java-docker
  services:
    - docker:dind
  stage: deploy
  dependencies:
    - microservice-build
  script:
    - cd /$CI_PROJECT_DIR/$JHIPSTER_MICROSERVICE_APP
    - ./mvnw docker:build
    - docker tag backend registry.gitlab.com/$GITLAB_GROUP/$GITLAB_PROJECT:$JHIPSTER_MICROSERVICE_APP
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/$GITLAB_GROUP/$GITLAB_PROJECT:$JHIPSTER_MICROSERVICE_APP
